In [1]:
import numpy as np

In [8]:
ar1=np.array(6)

In [9]:
ar1

array(6)

In [4]:
type(ar1)

numpy.ndarray

In [12]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [13]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
Array types

1. Zero Array
2. Ones Array
3. Empty Array
4. Array for range

In [15]:
zero_array=np.zeros(2)

In [16]:
zero_array

array([0., 0.])

In [38]:
ar3=np.arange(2,18,2)

In [39]:
ar3

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [40]:
ar4=np.transpose(ar2)

In [41]:
ar4

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [42]:
ar5=np.ravel(ar4)

In [43]:
ar5

array([1, 5, 2, 6, 3, 7, 4, 8])

In [46]:
concat=np.concatenate((ar5,ar3))

In [47]:
concat

array([ 1,  5,  2,  6,  3,  7,  4,  8,  2,  4,  6,  8, 10, 12, 14, 16])

In [48]:
hori=np.hstack((ar5,ar3))

In [49]:
hori

array([ 1,  5,  2,  6,  3,  7,  4,  8,  2,  4,  6,  8, 10, 12, 14, 16])

In [50]:
vert=np.vstack((ar5,ar3))

In [51]:
vert

array([[ 1,  5,  2,  6,  3,  7,  4,  8],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])