In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
ar1

array(6)

In [4]:
type(ar1)

numpy.ndarray

In [5]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
Array types

1. Zero Array
2. Ones Array
3. Empty Array
4. Array for range

SyntaxError: invalid syntax (3404234285.py, line 1)

In [8]:
zero_array=np.zeros(2)

In [9]:
zero_array

array([0., 0.])

In [10]:
ar3=np.arange(2,18,2)

In [11]:
ar3

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [12]:
ar4=np.transpose(ar2)

In [13]:
ar4

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
ar5=np.ravel(ar4)

In [15]:
ar5

array([1, 5, 2, 6, 3, 7, 4, 8])

In [16]:
concat=np.concatenate((ar5,ar3))

In [17]:
concat

array([ 1,  5,  2,  6,  3,  7,  4,  8,  2,  4,  6,  8, 10, 12, 14, 16])

In [18]:
hori=np.hstack((ar5,ar3))

In [19]:
hori

array([ 1,  5,  2,  6,  3,  7,  4,  8,  2,  4,  6,  8, 10, 12, 14, 16])

In [20]:
vert=np.vstack((ar5,ar3))

In [21]:
vert

array([[ 1,  5,  2,  6,  3,  7,  4,  8],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

In [24]:
mat=np.array([1,2,3])

In [52]:
mat1=np.array([[1,2,3],[3,5,6],[7,8,-3]])
mat1

array([[ 1,  2,  3],
       [ 3,  5,  6],
       [ 7,  8, -3]])

In [53]:
det_cf_mat1=np.linalg.det(mat1)

In [54]:
det_cf_mat1

6.0

In [56]:
inverse=np.linalg.inv(mat1)
inverse

array([[-10.5       ,   5.        ,  -0.5       ],
       [  8.5       ,  -4.        ,   0.5       ],
       [ -1.83333333,   1.        ,  -0.16666667]])

In [58]:
dense=mat1=np.array([[0,0,0,0,2],[0,0,0,5,6],[0,0,7,8,3]])

In [59]:
from scipy.sparse import csr_matrix

In [60]:
sparse=csr_matrix(dense)

In [61]:
sparse

<3x5 sparse matrix of type '<class 'numpy.int32'>'
	with 6 stored elements in Compressed Sparse Row format>

In [63]:
print(sparse)

  (0, 4)	2
  (1, 3)	5
  (1, 4)	6
  (2, 2)	7
  (2, 3)	8
  (2, 4)	3
